### ISSUE TITLE
Mutating/Validating admission webhook server breaks core controllers

### ISSUE THREAD

**Issue by sttts** [kubedb/project#634] opened 2019-08-28 13:51 UTC
The admission webhook server does not serve the `/apis/{mutators,validators}.kubedb.com/v1alpha1` endpoint. This breaks the namespace and quota controller in the cluster because those depend on discovery. 

My bet is that https://github.com/kubedb/operator/blob/master/pkg/server/server.go#L168 must not be empty.

**Comment by tamalsaha** [comment] 2019-08-29 07:03
@sttts , I just installed kubedb on a fresh minikube cluster. `kubectl api-resources` seems to be working for me.

```
~ $ minikube version
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631

~ $ minikube delete; minikube start
🔥  Deleting "minikube" in virtualbox ...
💔  The "minikube" cluster has been deleted.
😄  minikube v1.3.1 on Ubuntu 18.04
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
💾  Downloading kubelet v1.15.2
💾  Downloading kubeadm v1.15.2
🚜  Pulling images ...
🚀  Launching Kubernetes ... 
⌛  Waiting for: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"

~ $ kubectl version --short
Client Version: v1.15.0
Server Version: v1.15.2

~ $ curl -fsSL https://github.com/kubedb/installer/raw/v0.13.0-rc.0/deploy/kubedb.sh | bash

~ $ kubectl api-resources | grep kubedb
elasticsearchversions             esversion    catalog.kubedb.com             false        ElasticsearchVersion
etcdversions                      etcversion   catalog.kubedb.com             false        EtcdVersion
memcachedversions                 mcversion    catalog.kubedb.com             false        MemcachedVersion
mongodbversions                   mgversion    catalog.kubedb.com             false        MongoDBVersion
mysqlversions                     myversion    catalog.kubedb.com             false        MySQLVersion
postgresversions                  pgversion    catalog.kubedb.com             false        PostgresVersion
redisversions                     rdversion    catalog.kubedb.com             false        RedisVersion
dormantdatabases                  drmn         kubedb.com                     true         DormantDatabase
elasticsearches                   es           kubedb.com                     true         Elasticsearch
etcds                             etc          kubedb.com                     true         Etcd
memcacheds                        mc           kubedb.com                     true         Memcached
mongodbs                          mg           kubedb.com                     true         MongoDB
mysqls                            my           kubedb.com                     true         MySQL
postgreses                        pg           kubedb.com                     true         Postgres
redises                           rd           kubedb.com                     true         Redis
snapshots                         snap         kubedb.com                     true         Snapshot
elasticsearchmutators                          mutators.kubedb.com            false        AdmissionReview
etcdmutators                                   mutators.kubedb.com            false        AdmissionReview
memcachedmutators                              mutators.kubedb.com            false        AdmissionReview
mongodbmutators                                mutators.kubedb.com            false        AdmissionReview
mysqlmutators                                  mutators.kubedb.com            false        AdmissionReview
postgresmutators                               mutators.kubedb.com            false        AdmissionReview
redismutators                                  mutators.kubedb.com            false        AdmissionReview
dormantdatabasevalidators                      validators.kubedb.com          false        AdmissionReview
elasticsearchvalidators                        validators.kubedb.com          false        AdmissionReview
etcdvalidators                                 validators.kubedb.com          false        AdmissionReview
memcachedvalidators                            validators.kubedb.com          false        AdmissionReview
mongodbvalidators                              validators.kubedb.com          false        AdmissionReview
mysqlvalidators                                validators.kubedb.com          false        AdmissionReview
namespaces                                     validators.kubedb.com          false        AdmissionReview
postgresvalidators                             validators.kubedb.com          false        AdmissionReview
redisvalidators                                validators.kubedb.com          false        AdmissionReview
snapshotvalidators                             validators.kubedb.com          false        AdmissionReview
```

**Comment by tamalsaha** [comment] 2019-08-29 07:05
@sttts ,can you please show me the command that fails so that I can test this issue?

That particular line is same as openshift/generic-admission-server

https://github.com/openshift/generic-admission-server/blob/67ee169095686e03e4d7b889fd63a48f15b7e032/pkg/apiserver/apiserver.go#L133

**Comment by tamalsaha** [comment] 2019-08-29 07:10
I check the logs for kube-controller-manager pod. I see some errors but discovery is working now without any error. So, I am guessing those are transient errors.

```
I0829 06:41:30.754610       1 garbagecollector.go:137] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
W0829 06:57:08.998068       1 reflector.go:302] k8s.io/client-go/informers/factory.go:133: watch of *v1beta1.Event ended with: The resourceVersion for the provided watch is too old.
I0829 06:57:48.297204       1 event.go:258] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"kubedb-operator", UID:"6d31334c-3759-4331-a0df-59d6b0694c2d", APIVersion:"apps/v1", ResourceVersion:"1591", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set kubedb-operator-6f84c58bd6 to 1
I0829 06:57:48.307520       1 event.go:258] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"kubedb-operator-6f84c58bd6", UID:"2f169031-8342-4331-84fb-bd18beb924fd", APIVersion:"apps/v1", ResourceVersion:"1592", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
E0829 06:57:48.316815       1 replica_set.go:450] Sync "kube-system/kubedb-operator-6f84c58bd6" failed with pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
E0829 06:57:48.329403       1 replica_set.go:450] Sync "kube-system/kubedb-operator-6f84c58bd6" failed with pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
I0829 06:57:48.329852       1 event.go:258] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"kubedb-operator-6f84c58bd6", UID:"2f169031-8342-4331-84fb-bd18beb924fd", APIVersion:"apps/v1", ResourceVersion:"1596", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
E0829 06:57:48.337120       1 replica_set.go:450] Sync "kube-system/kubedb-operator-6f84c58bd6" failed with pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
I0829 06:57:48.337556       1 event.go:258] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"kubedb-operator-6f84c58bd6", UID:"2f169031-8342-4331-84fb-bd18beb924fd", APIVersion:"apps/v1", ResourceVersion:"1596", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
E0829 06:57:48.344435       1 replica_set.go:450] Sync "kube-system/kubedb-operator-6f84c58bd6" failed with pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
I0829 06:57:48.344672       1 event.go:258] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"kubedb-operator-6f84c58bd6", UID:"2f169031-8342-4331-84fb-bd18beb924fd", APIVersion:"apps/v1", ResourceVersion:"1596", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
E0829 06:57:48.395825       1 replica_set.go:450] Sync "kube-system/kubedb-operator-6f84c58bd6" failed with pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
I0829 06:57:48.396029       1 event.go:258] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"kubedb-operator-6f84c58bd6", UID:"2f169031-8342-4331-84fb-bd18beb924fd", APIVersion:"apps/v1", ResourceVersion:"1596", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
E0829 06:57:48.479279       1 replica_set.go:450] Sync "kube-system/kubedb-operator-6f84c58bd6" failed with pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
I0829 06:57:48.479463       1 event.go:258] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"kubedb-operator-6f84c58bd6", UID:"2f169031-8342-4331-84fb-bd18beb924fd", APIVersion:"apps/v1", ResourceVersion:"1596", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
E0829 06:57:48.649486       1 replica_set.go:450] Sync "kube-system/kubedb-operator-6f84c58bd6" failed with pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
I0829 06:57:48.649868       1 event.go:258] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"kubedb-operator-6f84c58bd6", UID:"2f169031-8342-4331-84fb-bd18beb924fd", APIVersion:"apps/v1", ResourceVersion:"1596", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "kubedb-operator-6f84c58bd6-" is forbidden: error looking up service account kube-system/kubedb-operator: serviceaccount "kubedb-operator" not found
I0829 06:57:49.979477       1 event.go:258] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"kubedb-operator-6f84c58bd6", UID:"2f169031-8342-4331-84fb-bd18beb924fd", APIVersion:"apps/v1", ResourceVersion:"1596", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: kubedb-operator-6f84c58bd6-hj62k
E0829 06:58:07.771884       1 resource_quota_controller.go:407] unable to retrieve the complete list of server APIs: mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request, validators.kubedb.com/v1alpha1: the server is currently unable to handle the request
I0829 06:58:07.800910       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for appbindings.appcatalog.appscode.com
I0829 06:58:07.801356       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for mysqls.kubedb.com
I0829 06:58:07.801520       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for etcds.kubedb.com
I0829 06:58:07.801667       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for snapshots.kubedb.com
I0829 06:58:07.801862       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for postgreses.kubedb.com
I0829 06:58:07.802055       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for elasticsearches.kubedb.com
I0829 06:58:07.802305       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for memcacheds.kubedb.com
I0829 06:58:07.802519       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for mongodbs.kubedb.com
I0829 06:58:07.802687       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for redises.kubedb.com
I0829 06:58:07.802889       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for dormantdatabases.kubedb.com
I0829 06:58:07.816572       1 controller_utils.go:1029] Waiting for caches to sync for resource quota controller
I0829 06:58:07.917196       1 controller_utils.go:1036] Caches are synced for resource quota controller
W0829 06:58:09.672928       1 garbagecollector.go:638] failed to discover some groups: map[mutators.kubedb.com/v1alpha1:the server is currently unable to handle the request validators.kubedb.com/v1alpha1:the server is currently unable to handle the request]
E0829 06:58:10.077850       1 memcache.go:199] couldn't get resource list for mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request
E0829 06:58:10.127373       1 memcache.go:199] couldn't get resource list for validators.kubedb.com/v1alpha1: the server is currently unable to handle the request
E0829 06:58:10.179603       1 memcache.go:111] couldn't get resource list for validators.kubedb.com/v1alpha1: the server is currently unable to handle the request
E0829 06:58:10.227938       1 memcache.go:111] couldn't get resource list for mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request
I0829 06:58:10.242758       1 controller_utils.go:1029] Waiting for caches to sync for garbage collector controller
I0829 06:58:10.348222       1 controller_utils.go:1036] Caches are synced for garbage collector controller


```

**Comment by sttts** [comment] 2019-08-29 07:17
Maybe the deployed kubedb version was old (don't have access anymore to that cluster). I just noticed that your code has v1 https://github.com/openshift/generic-admission-server/blob/67ee169095686e03e4d7b889fd63a48f15b7e032/pkg/apiserver/apiserver.go#L135, but I saw v1alpha1.

**Comment by tamalsaha** [comment] 2019-08-29 12:38
Thanks for reporting the issue regardless. We don't want to break cluster with webhooks :).

I looked at the documentation for `OptionsExternalVersion`

https://github.com/kubernetes/kubernetes/blob/7d4d17583bef4c9c0226e5d2803eec395567c5cb/staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go#L50

```
	// OptionsExternalVersion controls the Kubernetes APIVersion used for common objects in the apiserver
	// schema like api.Status, api.DeleteOptions, and metav1.ListOptions. Other implementors may
	// define a version "v1beta1" but want to use the Kubernetes "v1" internal objects. If
	// empty, defaults to GroupVersion.
	OptionsExternalVersion *schema.GroupVersion
```

`v1` seems to be the right value. Do you think otherwise?

**Comment by sttts** [comment] 2019-08-29 13:41
v1, yes.

**Comment by harshal-shah** [comment] 2019-09-02 14:11
Oddly, we are seeing a similar issue on one of our clusters. Other clusters are fine but only on this cluster we cannot delete namespaces as soon as the `ValidatingWebhookConfiguration` called `validators.kubedb.com` is created.
We see following messages in api-server logs 
~~~
W0902 01:14:08.834860 10 dispatcher.go:72] Failed calling webhook, failing closed namespace.validators.kubedb.com: failed calling webhook "namespace.validators.kubedb.com": the server was unable to return a response in the time allotted, but may still be processing the request
~~~

and nothing in kubedb-operator logs, we just get the following set of messages 

~~~
I0902 13:44:20.476592       1 xray.go:232] testing ValidatingWebhook using an object with GVR = kubedb.com/v1alpha1, Resource=redises
E0902 13:45:20.484596       1 status.go:64] apiserver received an error that is not an metav1.Status: http2.StreamError{StreamID:0x6a7, Code:0x0, Cause:error(nil)}
E0902 13:45:20.484656       1 writers.go:168] apiserver was unable to write a JSON response: http: Handler timeout
E0902 13:45:20.485718       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}
I0902 13:45:20.486838       1 trace.go:76] Trace[324192818]: "Create /apis/mutators.kubedb.com/v1alpha1/redismutators" (started: 2019-09-02 13:44:20.484396231 +0000 UTC m=+2835.021698694) (total time: 1m0.002422526s):
Trace[324192818]: [1m0.002422526s] [1m0.002422526s] END
~~~

**Comment by tamalsaha** [comment] 2019-09-02 17:24
@harshal-shah , 

1. can you please tell me how did you create the cluster so that I can recreate the scenario and test this?

2. From your error message, it seems that the operator is failing to respond to these webhook calls.

```
the server was unable to return a response in the time allotted, but may still be processing the request

apiserver received an error that is not an metav1.Status: http2.StreamError{StreamID:0x6a7, Code:0x0, Cause:error(nil)}
```

none of these error message are from KubeDB operator, rather look like networking issues at the cluster level.

Can you check the node where KubeDB operator pod is running has working network connection? If you restart the KubeDB operator pod and move it to different node in your cluster does that solve the issue?

3. Do you have any KubeDB object in that namespace and if yes, that is the value of their `spec.terminationPolicy` field? KubeDB has a feature where KubeDB operator will block deletion of a namespace if that namespace has KubeDB objects that are marked as `spec.terminationPolicy: DoNotTerminate` or `spec.terminationPolicy: Pause`. This was done to avoid accidental deletion of a database.

https://github.com/kubedb/apimachinery/blob/v0.13.0-rc.0/pkg/admission/namespace/admission.go#L102-L110

```
						terminationPolicy, found, err := unstructured.NestedString(u.Object, "spec", "terminationPolicy")
```

**Comment by antonu17** [comment] 2019-09-02 18:34
@tamalsaha thanks for the reply
@harshal-shah and I were working on troubleshooting the issue, so I can provide details.
1. It is EKS cluster running Kubernetes 1.13, nodes running amazon-eks-node-1.13-v20190614 (ami-09bbefc07310f7914)
2. We tried to re-create kubedb-operator pod on different nodes, the result was the same namespace deletion didn't work. Networking was our first suspect, but we were able to talk to kubernetes api from nodes as well as port forward kubedb-operator service and talk to it from a workstation. All nodes were re-created eventually to eliminate any possible glitches that may exist on "old" nodes.
3. It was an empty namespace, just created.

The worst is, it is only happening with the only one of our EKS clusters. Others work just fine. Empty namespaces get deleted "instantly", for those running KubeDB objects with `terminationPolicy` in `DoNotTerminate` or `Pause` - corresponding error message is shown by `kubectl delete namespace`.

**Comment by tamalsaha** [comment] 2019-09-02 18:40
> We tried to re-create kubedb-operator pod on different nodes, the result was the same namespace deletion didn't work. Networking was our first suspect, but we were able to talk to kubernetes api from nodes as well as port forward kubedb-operator service and talk to it from a workstation. All nodes were re-created eventually to eliminate any possible glitches that may exist on "old" nodes.

In case of validation webhooks, the kube-apiserver talks to the node where the operator pod is running (in the reverse direction). Is there a way to check if the kube-apiserver is able to do that?

> PS. Oh yes, namespace deletion it is not the only problem, creating any KubeDB object also hangs forever.

This means that the kube-apiserver can't make webhook calls to KubeDB operator.

**Comment by harshal-shah** [comment] 2019-09-02 20:00
Since this is a managed control plane, we cannot log on to the api-server pods or their associated nodes. We shall recheck our networking configs to make sure we haven't blocked any paths. We will update more on this tomorrow. Though via a quick look at our route tables and sec groups, we have everything in place as needed.

**Comment by tamalsaha** [comment] 2019-09-02 22:00
Is it possible to contact AWS and see if they can run any checks?

**Comment by harshal-shah** [comment] 2019-09-03 08:23
We checked our networking config and it looks fine. Moreover we have another mutating webhook which fetches secrets from vault and mounts them on pods. this mutator works fine as well. Is there any other way to figure out why the api-server wont talk to kubedb-operator service?

**Comment by tamalsaha** [comment] 2019-09-03 15:38
@harshal-shah , I would run kubedb-operator pod on the same host as the other working-mutating-webhook pod. So, run `kubectl get pods wokring-mutating-webhook -o yaml` and get its `spec.nodeName`. Then edit the the kubedb-operator to set the node selector.

`kubectl edit deployment -n kubedb-operator-ns kubedb-operator-deployment-name` .

That should restart the kubedb operator pod and move it to the same node. Then see if it works for not.

**Comment by cmoulliard** [comment] 2019-09-04 10:49
> don't have access anymore to that cluster

I redeployed kubedb 0.12 on a new cluster ocp4.1 running on AWS and having this config: t2.large, master is m4.xlarge and worker nodes are m4.4xlarge -> https://console-openshift-console.apps.cluster-bffb.bffb.sandbox171.opentlc.com/

I confirm that I suffer again of the same issues reported:
- We can't delete a namespace
```
 oc delete project test1
Error from server (InternalError): Internal error occurred: failed calling webhook "namespace.validators.kubedb.com": the server is currently unable to handle the request
```
- We have some authorization issues to access to get the API Resources
```
 kubectl api-resources | grep kubedb
elasticsearchversions                 esversion        catalog.kubedb.com                    false        ElasticsearchVersion
etcdversions                          etcversion       catalog.kubedb.com                    false        EtcdVersion
memcachedversions                     mcversion        catalog.kubedb.com                    false        MemcachedVersion
mongodbversions                       mgversion        catalog.kubedb.com                    false        MongoDBVersion
mysqlversions                         myversion        catalog.kubedb.com                    false        MySQLVersion
postgresversions                      pgversion        catalog.kubedb.com                    false        PostgresVersion
redisversions                         rdversion        catalog.kubedb.com                    false        RedisVersion
dormantdatabases                      drmn             kubedb.com                            true         DormantDatabase
elasticsearches                       es               kubedb.com                            true         Elasticsearch
etcds                                 etc              kubedb.com                            true         Etcd
memcacheds                            mc               kubedb.com                            true         Memcached
mongodbs                              mg               kubedb.com                            true         MongoDB
mysqls                                my               kubedb.com                            true         MySQL
postgreses                            pg               kubedb.com                            true         Postgres
redises                               rd               kubedb.com                            true         Redis
snapshots                             snap             kubedb.com                            true         Snapshot
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: Unauthorized, mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request, packages.operators.coreos.com/v1: Unauthorized, validators.kubedb.com/v1alpha1: the server is currently unable to handle the request
```
- Log of the kubedb pod reports this issue #639 

Config of the kubedb operator is 
```
          image: 'kubedb/operator:0.12.0'
          args:
            - run
            - '--v=3'
            - '--governing-service=kubedb'
            - '--rbac=true'
            - '--secure-port=8443'
            - '--audit-log-path=-'
            - '--tls-cert-file=/var/serving-cert/tls.crt'
            - '--tls-private-key-file=/var/serving-cert/tls.key'
            - '--enable-mutating-webhook=true'
            - '--enable-validating-webhook=true'
            - '--enable-status-subresource=true'
            - '--bypass-validating-webhook-xray=false'
            - '--use-kubeapiserver-fqdn-for-aks=true'
            - '--enable-analytics=true'
```

**Comment by cmoulliard** [comment] 2019-09-04 11:03
> That should restart the kubedb operator

I did what you suggested after looking to the Tekton Webhook pod (which is running on this cluster) and which contains this value as `nodeselector`
```
spec:
  nodeSelector:
    #beta.kubernetes.io/arch: amd64
    # beta.kubernetes.io/os: linux
    nodeName: ip-10-0-135-246.ap-southeast-1.compute.internal
```

but unfortunately the kubedb pod can't start as it can't find a matching
```
0/2 nodes are available: 2 node(s) didn't match node selector.
```

As this is more than blocking, your help is more then appreciated @tamalsaha 

FYI: @sttts

**Comment by harshal-shah** [comment] 2019-09-04 13:56
Continuing our investigation further, we installed the kubedb-operator pod on same node as vault injector and it still gave the same error. 
We also tried one more mutator https://github.com/stackrox/admission-controller-webhook-demo and it worked fine on that cluster as well so this does not seem to be a issue with api-server not being able to reach the webhook service. 

One thing that we noted was different between kubedb operator's webhooks versus others was that the other webhook configurations call the service of the operator directly in the clientconfig 
For example: 
~~~
webhooks:
- clientConfig:
    caBundle: SOME-CA
    service:
      name: istio-galley
      namespace: istio-system
      path: /admitmixer
~~~

but in case of kubedb we call the kubernetes service in default namespace

~~~
- clientConfig:
    caBundle: SOME-CA
    service:
      name: kubernetes
      namespace: default
      path: /apis/mutators.kubedb.com/v1alpha1/elasticsearchmutators
~~~

**Comment by cmoulliard** [comment] 2019-09-04 17:34
> but in case of kubedb we call the kubernetes service in default namespace

I don't think that the issue is there because if we look to Tiller Webhook deployed under `kube-system`, then the `clientconfig / service` is also defined as `default`

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
...
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook
webhooks:
- clientConfig:
    caBundle: 
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.certmanager.k8s.io/v1beta1/certificates
```

**Comment by harshal-shah** [comment] 2019-09-06 21:39
We were finally able to fix the issue. We had one more of our internal operators running on the cluster which did not have either mutating or validating hooks but somehow as soon as we deleted the operator, kubedb started working fine. We are unable to reproduce this issue but we will post if we find anything else.

**Comment by skad0Osh** [comment] 2019-10-25 02:07
i tried the workarounds nothing works
i set deployment.spec.template.spec.nodeName for kubedb operato and postgres operator to the same server as where kube-apiserver was on running but still nothing  .. any other suggestions ?
I created a simple webhook and that works ok

operator log shows:```
1017 02:53:16.320838       1 status.go:64] apiserver received an error that is not an metav1.Status: http2.StreamError{StreamID:0x7, Code:0x8, Cause:error(nil)}
I1017 02:53:16.321233       1 trace.go:76] Trace[629458047]: “Create /apis/mutators.kubedb.com/v1alpha1/postgreses” (started: 2019-10-17 02:52:46.321671667 +0000 UTC m=+84.700306066) (total time: 29.999520351s):
Trace[629458047]: [29.999520351s] [29.999520351s] END

**Comment by Quentin-M** [comment] 2020-04-21 18:16
We had an event yesterday where we had to restore one of our clusters from an etcd snapshot. During the recovery of the control plane, our queries to the API server on namespaces and all would all fail as the kube-db was not ready:

```
the server is currently unable to handle the request, validators.kubedb.com/v1alpha1: the server is currently unable to handle the request
```

```
I0421 06:56:12.914796       1 controller.go:107] OpenAPI AggregationController: Processing item v1alpha1.mutators.kubedb.com
[11:56 PM] E0421 06:56:12.914915       1 controller.go:114] loading OpenAPI spec for "v1alpha1.mutators.kubedb.com" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
```

**Comment by tamalsaha** [comment] 2020-04-21 19:16
What I have seen is that Kubernetes Discovery api calls will return with a`discovery.IsGroupDiscoveryFailedError(err)` if one of the APIService is not ready. If KubeDB operator pod is not ready, the related APIService becomes not ready. This is not a KubeDB specific issue. This will happen any APIService you have running in the cluster.

In our Go code, we just ignore this error, since the api server returns discovery result for other apis it can discover. https://github.com/kmodules/client-go/blob/1b13a5bf7a46fa4f66d22ab0022854a343081c80/discovery/restmapper.go#L58-L63

So, "our queries to the API server on namespaces and all would all fail as the kube-db was not ready". What kind of query are you running? This seems like an issue that should be raised at upstream k/k.

**Comment by blacs30** [comment] 2020-07-07 20:02
I think I see similar logs. 
On the kube apiserver I get these 4 logs every minute. Kubedb itself is running fine. 

```
E0707 19:59:07.476331       1 controller.go:114] loading OpenAPI spec for "v1alpha1.validators.kubedb.com" failed with: OpenAPI spec does not exist
I0707 19:59:07.476359       1 controller.go:127] OpenAPI AggregationController: action for item v1alpha1.validators.kubedb.com: Rate Limited Requeue.
E0707 19:59:07.477197       1 controller.go:114] loading OpenAPI spec for "v1alpha1.mutators.kubedb.com" failed with: OpenAPI spec does not exist
I0707 19:59:07.477471       1 controller.go:127] OpenAPI AggregationController: action for item v1alpha1.mutators.kubedb.com: Rate Limited Requeue.
```

Version 0.13.0.rc.0
Installed via `helm template` and then `kubectl apply -f`

**Comment by Teingi** [comment] 2021-02-25 08:51
I think I see similar errors.

`I0225 08:33:26.746303       1 secure_serving.go:116] Serving securely on [::]:8443
I0225 08:33:29.591785       1 xray.go:232] testing ValidatingWebhook using an object with GVR = service.diamond.sensetime.com/v1alpha1, Resource=mongodbs
E0225 08:35:33.844163       1 status.go:71] apiserver received an error that is not an metav1.Status: http2.StreamError{StreamID:0x33, Code:0x8, Cause:error(nil)}
I0225 08:35:33.845933       1 trace.go:81] Trace[208240456]: "Create /apis/mutators.mongodb.service.kubedb.com/v1alpha1/mongodbmutators" (started: 2021-02-25 08:35:03.846968176 +0000 UTC m=+101.993557476) (total time: 29.998932662s):
Trace[208240456]: [29.998932662s] [29.998932662s] END`

**Comment by starcraft66** [comment] 2021-03-06 19:14
I'm experiencing the exact same issue on a bare metal cluster created with kubespray and a local cluster created with kind.

**Comment by tamalsaha** [comment] 2021-03-19 19:26
This has been resolved here: https://github.com/kubedb/installer/pull/266

**Closed by tamalsaha** 2021-03-19 19:26 UTC
