### ISSUE TITLE
Backups require admin permission for GCS

### ISSUE THREAD

**Issue by 0nkery** [kubedb/project#208] opened 2018-07-23 18:54 UTC
Hi!
I am trying to setup backup for PSQL db using KubeDB.

Here is my backup config:

```
  backupSchedule:
    cronExpression: "@every 6h"
    storageSecretName: gcs-secret
    gcs:
      bucket: finrazor-postgres-backup
```

I created `gcs-secret` and bucket `finrazor-postgres-backup` but when I am trying to apply this config to cluster I get the following error:

```
Error from server (Forbidden): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"kubedb.com/v1alpha1\",\"kind\":\"Postgres\",\"metadata\":{\"annotations\":{},\"name\":\"finrazor-postgres\",\"namespace\":\"default\"},\"spec\":{\"backupSchedule\":{\"cronExpression\":\"@every 6h\",\"gcs\":{\"bucket\":\"finrazor-postgres-backup\"},\"storageSecretName\":\"gcs-secret\"},\"doNotPause\":true,\"replicas\":2,\"standbyMode\":\"hot\",\"storage\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"limits\":{\"storage\":\"5Gi\"},\"requests\":{\"storage\":\"500Mi\"}},\"storageClassName\":\"standard\"},\"version\":\"10.2\"}}\n"}},"spec":{"backupSchedule":{"cronExpression":"@every 6h","gcs":{"bucket":"finrazor-postgres-backup"},"storageSecretName":"gcs-secret"}}}
to:
Resource: "kubedb.com/v1alpha1, Resource=postgreses", GroupVersionKind: "kubedb.com/v1alpha1, Kind=Postgres"
Name: "finrazor-postgres", Namespace: "default"
Object: &{map["metadata":map["creationTimestamp":"2018-07-23T18:13:34Z" "generation":'\x01' "name":"finrazor-postgres" "resourceVersion":"42517" "clusterName":"" "finalizers":["kubedb.com"] "namespace":"default" "selfLink":"/apis/kubedb.com/v1alpha1/namespaces/default/postgreses/finrazor-postgres" "uid":"1cab8772-8ea4-11e8-95c0-42010a800076"] "spec":map["databaseSecret":map["secretName":"finrazor-postgres-auth"] "doNotPause":%!q(bool=true) "replicas":'\x02' "standbyMode":"hot" "storage":map["accessModes":["ReadWriteOnce"] "resources":map["limits":map["storage":"5Gi"] "requests":map["storage":"500Mi"]] "storageClassName":"standard"] "version":"10.2"] "status":map["creationTime":"2018-07-23T18:13:34Z" "phase":"Running"] "apiVersion":"kubedb.com/v1alpha1" "kind":"Postgres"]}
for: "k8s/postgres.yml": admission webhook "postgres.validators.kubedb.com" denied the request: not found
```

Since error message is not so informative I cannot understand what the problem is. Could you please help me to find out the root cause?

PS. My role setup is based on new GCS roles: ObjectCreator and ObjectViewer.

**Comment by tamalsaha** [comment] 2018-08-15 00:51
I have looked into this. This is what I found. 

We [used to check](https://github.com/kubedb/project/issues/173) for [bucket access](https://github.com/kmodules/objectstore-api/blob/5437829d6e1c97de1c3effe5f2dc6cbca2e0bfd4/osm/osm.go#L92) via ValidatingWebhook for db crds. The check process will confirm 2 things:

1. Bucket specified in db crd [exists](https://github.com/kmodules/objectstore-api/blob/5437829d6e1c97de1c3effe5f2dc6cbca2e0bfd4/osm/osm.go#L105).

2. Write access to bucket is provided. This is done by first writing a test file and deleting it. We delete the file so that such test files don't clutter to bucket. 

If you look at the [IAM docs for GCS buckets](https://cloud.google.com/storage/docs/access-control/iam-roles), you will find this: 
![gcs-iam](https://user-images.githubusercontent.com/94814/44126017-9fb6056c-9fea-11e8-9de2-b3edaca6eb18.png)

This is where the problem is. Checking `write` access, itself requires admin permission. :(

**Comment by tamalsaha** [comment] 2018-08-15 00:56
Solution:

This write access check is now removed from `ValidatingWebhook` and moved to actual Snapshot job. So, `objectAdmin` permission is still required.

The proper fix will be to use to the [`testIamPermissions`](https://cloud.google.com/storage/docs/json_api/v1/buckets/testIamPermissions). This will require pluming this through the Stow library.

**Comment by tamalsaha** [comment] 2018-08-15 02:31
Should be fixed in master after revendoring.

**Closed by tamalsaha** 2018-08-15 02:31 UTC
Labels: bug, cloud-credential
